# This is a basic workflow to help you get started with Actions

name: 🚀 Deploy React Website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 🔧 Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 💽 Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: 📃 Writing Staging Env
        if: ${{ steps.extract_branch.outputs.branch == 'development' }}
        run: printf "REACT_APP_BASE_URL=${{ secrets.STAGING_BASE_URL }}" > .env

      - name: 📃 Writing Production Env
        if: ${{ steps.extract_branch.outputs.branch == 'main' }}
        run: printf "REACT_APP_BASE_URL=${{ secrets.PRODUCTION_BASE_URL }}" > .env

      - name: ⌛ Installing Package
        run: npm install

      - name: ⌛ Building React App
        run: npm run build

      - name: 💾 Saving React Build File
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: react-ga-build
          # A file, directory or wildcard pattern that describes what to upload
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Download previously shared build
      - name: 💾 Download Build File
        uses: actions/download-artifact@v1
        with:
          name: react-ga-build
          path: ~/react-ga-build

      - name: 📂 Sync files
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude=".git" --exclude=".github"
          path: ~/react-ga-build
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_port: 65002
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
